"""
Tying it together: models in, a NewGRF out.

(The module is `builder`, not `project`, so that `newgrfengine.project` stays
the isometric projection function - importing a submodule of that name would
quietly shadow it.)

A vehicle set has a shape that barely varies between projects. Every vehicle
has an identifier, a name, a model, a prototype length, a slot, some
properties, and a line of purchase text; every set has a sheet, a .pnml, a
language file, and a call to nmlc at the end. This module holds that shape so
a project can be a table of vehicles and a build script of about ten lines.

Nothing here is required to use the renderer. Everything below is written in
terms of the public pieces - render, sheet, nmlwrite - and a project with its
own ideas about NML can use those directly and skip this.

The one opinion worth stating: `length_ft` and `slot` are separate fields and
both are required. Together they are what stops a set drawing a switcher the
same length as a diner, and the build report prints how much of its slot each
vehicle actually filled so a wrong figure is visible immediately rather than
three days later in a screenshot.
"""

from __future__ import annotations

import os
import re
import subprocess
from numbers import Integral

from . import nmlwrite as nw
from .model import Model
from .preview import consist, contact_sheet
from .render import DEFAULT, render_model, render_purchase
from .scale import RAIL
from .sheet import TIGHT, SpriteSheet

TRAIN = "FEAT_TRAINS"
ROADVEH = "FEAT_ROADVEHS"

#: Setting this is what tells OpenTTD the item carries its own graphics.
SPRITE_ID = {TRAIN: "SPRITE_ID_NEW_TRAIN", ROADVEH: "SPRITE_ID_NEW_ROADVEH"}


class IntParam:
    """One integer GRF parameter, with names and variant keys kept together.

    ``values`` maps the integer stored by OpenTTD to its user-facing name.  A
    vehicle may address a non-default value by number, by that name converted
    to ``snake_case``, or by an explicit alias.  Thus ``"Game-balanced"`` can
    be written as ``variants={"balanced": {...}}`` without repeating the
    parameter value throughout a fleet table.

    The language keys and the NML ``param`` block are generated by Project.
    This keeps a realistic/balanced switch as data instead of a hand-written
    guard whose position in the file is easy to get wrong.
    """

    def __init__(self, number, name, values, default=0, label=None, desc=None,
                 aliases=None):
        if not values:
            raise ValueError("an integer parameter needs at least one value")
        if default not in values:
            raise ValueError("default {!r} is not in values".format(default))
        self.number = int(number)
        self.name = str(name)
        self.values = dict(values)
        self.default = default
        self.label = label or self.name.replace("_", " ").title()
        self.desc = desc or "Choose {}.".format(self.label.lower())
        self.aliases = {
            self._slug(alias): value for alias, value in (aliases or {}).items()
        }

        candidates = {}
        ambiguous = set()
        for value, text in self.values.items():
            slug = self._slug(text)
            for alias in (slug, slug.rsplit("_", 1)[-1]):
                if alias in candidates and candidates[alias] != value:
                    ambiguous.add(alias)
                else:
                    candidates[alias] = value
        for alias in ambiguous:
            candidates.pop(alias, None)
        for alias, value in candidates.items():
            self.aliases.setdefault(alias, value)

        unknown = set(self.aliases.values()) - set(self.values)
        if unknown:
            raise ValueError("variant aliases name unknown values: {}".format(
                sorted(unknown)))

    @staticmethod
    def _slug(value):
        return re.sub(r"[^a-z0-9]+", "_", str(value).lower()).strip("_")

    @property
    def _lang_prefix(self):
        return "STR_PARAM_{}".format(
            re.sub(r"[^A-Z0-9]+", "_", self.name.upper()).strip("_"))

    def resolve(self, key):
        """Resolve a Vehicle.variants key to the parameter's integer value."""
        if key in self.values:
            return key
        alias = self._slug(key)
        if alias in self.aliases:
            return self.aliases[alias]
        raise ValueError(
            "unknown {!r} variant for parameter {!r}; use one of {}".format(
                key, self.name, sorted(self.aliases)))

    def add_lang(self, lang):
        lang.strings.setdefault(self._lang_prefix + "_NAME", self.label)
        lang.strings.setdefault(self._lang_prefix + "_DESC", self.desc)
        for value, text in self.values.items():
            lang.strings.setdefault(
                "{}_{}".format(self._lang_prefix, value), str(text))

    def nml(self):
        names = {
            value: nw.string("{}_{}".format(self._lang_prefix, value))
            for value in self.values
        }
        return nw.int_param(
            self.number, self.name,
            nw.string(self._lang_prefix + "_NAME"),
            nw.string(self._lang_prefix + "_DESC"),
            names, default=self.default)


class Vehicle:
    """One buyable vehicle: what it looks like, how long it is, what it does.

    `numeric_id` optionally pins its NML item ID (0..65535). Keep published
    IDs stable across roster edits; None leaves allocation to nmlc.
    """

    def __init__(self, ident, name, model, length_ft, slot, feature=TRAIN,
                 scale=RAIL, properties=None, graphics=None, purchase=None,
                 overhang=0.0, buy_sprite=True, variants=None, numeric_id=None,
                 **meta):
        self.ident = ident
        self.name = name
        self._model = model
        self.length_ft = float(length_ft)
        if not 1 <= int(slot) <= 8:
            raise ValueError(
                "slot must be 1..8 - it is the NML `length` property, in "
                "eighths of a tile; got {!r}".format(slot))
        self.slot = int(slot)
        self.feature = feature
        self.numeric_id = numeric_id
        self._validate_numeric_id()
        self.scale = scale
        self.properties = dict(properties or {})
        self.graphics = dict(graphics or {})
        self.variants = {
            key: dict(settings) for key, settings in (variants or {}).items()
        }
        self.purchase = purchase
        self.overhang = float(overhang)
        self.buy_sprite = buy_sprite
        self.drawn = None
        self.dimensions = None
        #: Columns the fleet table carries that the engine itself does not
        #: model (kind, balanced_speed, ...) - kept here so the table stays
        #: the single source of truth instead of a parallel dict at the call
        #: site. See issue #7.
        self.meta = meta

    def _validate_numeric_id(self):
        if self.numeric_id is not None and (
                isinstance(self.numeric_id, bool)
                or not isinstance(self.numeric_id, Integral)
                or not 0 <= self.numeric_id <= 65535):
            raise ValueError(
                "vehicle {!r}: numeric_id must be an integer in 0..65535 "
                "or None; got {!r}".format(self.ident, self.numeric_id))

    def build_model(self):
        """The model, fitted to its prototype length and its slot."""
        model = self._model() if callable(self._model) else self._model
        fitted, drawn = self.scale.fit(Model(model), self.length_ft, self.slot,
                                       self.overhang)
        self.drawn = drawn
        self.dimensions = tuple(hi - lo for lo, hi in fitted.bbox())
        return fitted

    @property
    def capped(self):
        return self.scale.is_capped(self.length_ft, self.slot, self.overhang)

    @property
    def name_key(self):
        return "STR_NAME_{}".format(self.ident.upper())

    @property
    def purchase_key(self):
        return "STR_PURCHASE_{}".format(self.ident.upper())

    def __repr__(self):
        return "Vehicle({!r}, {:.0f} ft in {}/8)".format(
            self.ident, self.length_ft, self.slot)


class Project:
    """A whole set: vehicles, a sheet, a .pnml, a language file, a .grf."""

    def __init__(self, name, grfid, title, description, version=1,
                 min_compatible_version=1, out_dir=".", layout=TIGHT,
                 spec=DEFAULT, sprite_dir="sprites", lang_dir="lang",
                 cargotable=("PASS", "MAIL"), railtypetable=("RAIL", "ELRL"),
                 roadtypetable=None, params=(), variant_param=None,
                 header=None):
        self.name = name
        self.grfid = grfid
        self.title = title
        self.description = description
        self.version = version
        self.min_compatible_version = min_compatible_version
        self.out_dir = out_dir
        self.layout = layout
        self.spec = spec
        self.sprite_dir = sprite_dir
        self.lang_dir = lang_dir
        self.cargotable = cargotable
        self.railtypetable = railtypetable
        self.roadtypetable = roadtypetable
        self.params = list(params)
        if variant_param is not None and not isinstance(variant_param, IntParam):
            raise TypeError("variant_param must be an IntParam")
        self.variant_param = variant_param
        self.header = header
        self.vehicles = []
        self.extra_nml = []
        self.lang = nw.Lang()
        self.sheet = None
        self.rendered = {}

    # -- assembly -------------------------------------------------------------

    def add(self, vehicle):
        self._validate_vehicles(self.vehicles + [vehicle])
        self.vehicles.append(vehicle)
        return vehicle

    def _validate_vehicles(self, vehicles=None):
        """Check identities before rendering or emitting project output.

        Recheck at output time because fleet tables and Vehicle fields remain
        mutable after add(). Numeric IDs are local to each NML feature, while
        item identifiers and generated language keys are global.
        """
        identifiers, keys, numeric_ids = {}, {}, {}
        for vehicle in self.vehicles if vehicles is None else vehicles:
            ident = vehicle.ident
            if ident in identifiers:
                raise ValueError("duplicate vehicle identifier {!r}".format(ident))
            identifiers[ident] = vehicle
            for key in (vehicle.name_key, vehicle.purchase_key):
                if key in keys:
                    raise ValueError(
                        "vehicles {!r} and {!r} share generated language key {}"
                        .format(keys[key], ident, key))
                keys[key] = ident
            vehicle._validate_numeric_id()
            if vehicle.numeric_id is not None:
                key = (vehicle.feature, vehicle.numeric_id)
                if key in numeric_ids:
                    raise ValueError(
                        "vehicles {!r} and {!r} share numeric_id {} in {}"
                        .format(numeric_ids[key], ident, vehicle.numeric_id,
                                vehicle.feature))
                numeric_ids[key] = ident

    def vehicle(self, *args, **kwargs):
        return self.add(Vehicle(*args, **kwargs))

    def add_nml(self, text, heading=None, position="before_items"):
        """Raw NML - switches, callbacks, anything this module does not model.

        `position` is where the text lands relative to the generated item()
        blocks: "before_items" (the default - templates, spritesets, switches
        that the properties below reference) or "after_items", which is where
        a parameter-guarded override block belongs. NML applies Action 0
        records in file order, so an override emitted *before* the base
        definition it is meant to change is silently overwritten by it rather
        than the other way around.
        """
        if position not in ("before_items", "after_items"):
            raise ValueError(
                "position must be 'before_items' or 'after_items', got {!r}"
                .format(position))
        self.extra_nml.append((text, heading, position))
        return self

    # -- paths ----------------------------------------------------------------

    def path(self, *parts):
        return os.path.join(self.out_dir, *parts)

    @property
    def sheet_name(self):
        return os.path.join(self.sprite_dir, self.name + ".png")

    # -- rendering ------------------------------------------------------------

    def render(self, verbose=True):
        """Render every vehicle and pack the sheet."""
        self._validate_vehicles()
        self.sheet = SpriteSheet(self.name, layout=self.layout)
        self.rendered = {}
        for vehicle in self.vehicles:
            model = vehicle.build_model()
            sprites = render_model(model, self.spec)
            buy = render_purchase(model, self.spec) if vehicle.buy_sprite else None
            self.sheet.add(vehicle.ident, sprites, purchase=buy)
            self.rendered[vehicle.ident] = sprites
            if verbose:
                print(self._report(vehicle))
        return self.sheet

    def _report(self, v):
        x, y, z = v.dimensions
        notes = []
        if v.capped:
            notes.append("capped")
        if z > x:
            notes.append("WARN taller than long")
        return ("{:<20} {:5.2f} of {} units  ({:3.0f}% of slot)  {:>5.0f} ft"
                "   {:4.1f} x {:4.1f} x {:4.1f}{}".format(
                    v.ident, v.drawn, v.slot, 100.0 * v.drawn / v.slot,
                    v.length_ft, x, y, z,
                    "  " + ", ".join(notes) if notes else ""))

    # -- output ---------------------------------------------------------------

    def write_sprites(self):
        return self.sheet.save(self.path(self.sheet_name))

    def write_lang(self, filename="english.lng"):
        self._validate_vehicles()
        lang = self.lang
        lang.strings.setdefault("STR_GRF_NAME", self.title)
        lang.strings.setdefault("STR_GRF_DESC", self.description)
        if self.variant_param:
            self.variant_param.add_lang(lang)
        for v in self.vehicles:
            lang.strings.setdefault(v.name_key, v.name)
            if v.purchase:
                lang.strings.setdefault(v.purchase_key, v.purchase)
        return lang.write(self.path(self.lang_dir, filename))

    def nml_text(self):
        self._validate_vehicles()
        doc = nw.NML(self.header or self._default_header())
        params = list(self.params)
        if self.variant_param:
            params.append(self.variant_param.nml())
        doc.add(nw.grf_block(self.grfid, nw.string("STR_GRF_NAME"),
                             nw.string("STR_GRF_DESC"), self.version,
                             self.min_compatible_version, params))
        tables = []
        if self.cargotable:
            tables.append(nw.table("cargotable", self.cargotable))
        if self.railtypetable:
            tables.append(nw.table("railtypetable", self.railtypetable))
        if self.roadtypetable:
            tables.append(nw.table("roadtypetable", self.roadtypetable))
        if tables:
            doc.add("".join(tables))
        doc.add(self.sheet.nml_templates(), heading="sprite templates")
        doc.add(self.sheet.nml_spritesets(self.sheet_name), heading="spritesets")
        for text, heading, position in self.extra_nml:
            if position == "before_items":
                doc.add(text, heading=heading)
        # nmlc allocates IDs in file order. Define explicit IDs first so an
        # earlier automatic vehicle cannot silently claim the same ID.
        item_order = sorted(self.vehicles, key=lambda v: v.numeric_id is None)
        doc.add("\n\n".join(self._item(v) for v in item_order),
                heading="vehicles")
        variants = self._variant_nml()
        if variants:
            doc.add(variants, heading="property variants")
        for text, heading, position in self.extra_nml:
            if position == "after_items":
                doc.add(text, heading=heading)
        return doc.text()

    def _item(self, v):
        properties = self._base_properties(v)
        graphics = {"default": "ss_" + v.ident}
        if v.buy_sprite:
            graphics["purchase"] = "ss_{}_buy".format(v.ident)
        if v.purchase:
            # NML calls the purchase-window blurb `additional_text`, which is
            # easy to go looking for under the wrong name.
            graphics["additional_text"] = nw.string(v.purchase_key)
        graphics.update(v.graphics)
        return nw.item(v.feature, v.ident, properties, graphics,
                       numeric_id=v.numeric_id,
                       comment="{} - {:.0f} ft prototype".format(v.name, v.length_ft))

    @staticmethod
    def _base_properties(v):
        properties = {"name": nw.string(v.name_key), "length": v.slot}
        properties.update(v.properties)
        properties.setdefault("climates_available", "ALL_CLIMATES")
        properties.setdefault("sprite_id", SPRITE_ID[v.feature])
        return properties

    def _resolved_variants(self, vehicle):
        if vehicle.variants and not self.variant_param:
            raise ValueError(
                "vehicle {!r} has variants but Project has no variant_param"
                .format(vehicle.ident))
        resolved = {}
        for key, properties in vehicle.variants.items():
            value = self.variant_param.resolve(key)
            if value == self.variant_param.default:
                raise ValueError(
                    "vehicle {!r} supplies an override for the default variant"
                    .format(vehicle.ident))
            if value in resolved:
                raise ValueError(
                    "vehicle {!r} names variant value {} more than once".format(
                        vehicle.ident, value))
            resolved[value] = properties
        return resolved

    def _variant_nml(self):
        if not self.variant_param:
            for vehicle in self.vehicles:
                if vehicle.variants:
                    self._resolved_variants(vehicle)
            return ""

        by_value = {value: [] for value in self.variant_param.values
                    if value != self.variant_param.default}
        for vehicle in self.vehicles:
            base = self._base_properties(vehicle)
            for value, properties in self._resolved_variants(vehicle).items():
                changed = {key: setting for key, setting in properties.items()
                           if setting is not None and base.get(key) != setting}
                if changed:
                    by_value[value].append(nw.item(
                        vehicle.feature, vehicle.ident, changed,
                        comment="{}: {}".format(
                            vehicle.name, self.variant_param.values[value])))

        blocks = []
        for value in self.variant_param.values:
            items = by_value.get(value, [])
            if not items:
                continue
            body = nw._indent("\n\n".join(items), 4)
            blocks.append("if ({} == {}) {{\n{}\n}}".format(
                self.variant_param.name, value, body))
        return "\n\n".join(blocks)

    def variant_report(self):
        """A Markdown table of effective property values for every variant."""
        if not self.variant_param:
            raise RuntimeError("Project has no variant_param")

        headings = [self.variant_param.values[value]
                    for value in self.variant_param.values]
        rows = []
        for vehicle in self.vehicles:
            base = self._base_properties(vehicle)
            overrides = self._resolved_variants(vehicle)
            keys = set()
            for properties in overrides.values():
                keys.update(key for key, setting in properties.items()
                            if setting is not None and base.get(key) != setting)
            for key in sorted(keys):
                values = []
                for value in self.variant_param.values:
                    setting = overrides.get(value, {}).get(key, base.get(key))
                    values.append(self._report_cell(setting))
                rows.append([vehicle.ident, key] + values)

        if not rows:
            return "No variant differences.\n"
        header = ["Vehicle", "Property"] + [str(value) for value in headings]
        lines = ["| " + " | ".join(header) + " |",
                 "| " + " | ".join("---" for _ in header) + " |"]
        lines += ["| " + " | ".join(row) + " |" for row in rows]
        return "\n".join(lines) + "\n"

    @staticmethod
    def _report_cell(value):
        if value is None:
            return "—"
        return str(value).replace("|", "\\|").replace("\n", " ")

    def write_nml(self, filename=None):
        filename = filename or (self.name + ".pnml")
        path = self.path(filename)
        directory = os.path.dirname(os.path.abspath(path))
        if directory:
            os.makedirs(directory, exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(self.nml_text())
        return path

    def _default_header(self):
        return ("{}\n\nGenerated by newGRFengine - edit the project, not this "
                "file.\nEvery sprite here is projected from a 3D model into "
                "OpenTTD's own\nisometric mapping, and every template offset "
                "below was computed from\nthe rendered geometry rather than "
                "measured by hand.".format(self.title))

    # -- previews -------------------------------------------------------------

    def _require_rendered(self):
        if not self.rendered:
            raise RuntimeError(
                "call render() or build() before writing a preview")

    def write_preview(self, filename=None, scale=4, reference=None):
        self._require_rendered()
        filename = filename or (self.name + "_preview.png")
        entries = [(v.ident, self.rendered[v.ident]) for v in self.vehicles]
        path = self.path(filename)
        contact_sheet(entries, scale=scale, reference=reference).save(path)
        return path

    def write_consist(self, idents, filename=None, direction=1, scale=4,
                      reference=None):
        """A preview of the named vehicles coupled up, at the game's spacing."""
        self._require_rendered()
        filename = filename or (self.name + "_consist.png")
        by_id = {v.ident: v for v in self.vehicles}
        items = [(self.rendered[i], by_id[i].slot) for i in idents]
        path = self.path(filename)
        consist(items, direction=direction, scale=scale,
                reference=reference).save(path)
        return path

    # -- compiling ------------------------------------------------------------

    def compile(self, grf=None, nmlc="nmlc", extra_args=()):
        """Run nmlc over the generated .pnml.

        nmlc resolves the sprite filenames inside a spriteset against its own
        working directory, so it is run from the project directory with
        everything named relatively - which is also what keeps the generated
        .pnml portable between machines.
        """
        grf = grf or (self.name + ".grf")
        cmd = [nmlc, "--grf", grf, "--lang-dir", self.lang_dir,
               self.name + ".pnml"] + list(extra_args)
        result = subprocess.run(cmd, cwd=self.out_dir or ".",
                                capture_output=True, text=True)
        return result, self.path(grf)

    def build(self, verbose=True, preview=True, compile_grf=False):
        """Render, write everything, and optionally call nmlc."""
        self.render(verbose=verbose)
        paths = {"sprites": self.write_sprites(),
                 "lang": self.write_lang(),
                 "nml": self.write_nml()}
        if preview:
            paths["preview"] = self.write_preview()
        if compile_grf:
            result, grf = self.compile()
            if result.returncode != 0:
                raise RuntimeError("nmlc failed:\n{}\n{}".format(
                    result.stdout, result.stderr))
            paths["grf"] = grf
        return paths
